version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "rymsha"
    reviewers:
      - "rymsha"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
      exclude:
        - "@enonic-types/*"
    open-pull-requests-limit: 10
    assignees:
      - "alansemenov"
    reviewers:
      - "alansemenov"
    groups:
      enonic-types:
        patterns:
          - "@enonic-types/*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    assignees:
      - "rymsha"
    reviewers:
      - "rymsha"
