[versions]
enonic-defaults = "2.1.7"
graphql-java = "26.1"
graphql-java-extended-scalars = "24.0"
junit = "6.1.3"
mockito = "5.24.0"
node-gradle = "7.1.0"

[plugins]
enonic-defaults = { id = "com.enonic.defaults", version.ref = "enonic-defaults" }
node-gradle = { id = "com.github.node-gradle.node", version.ref = "node-gradle" }

[libraries]
graphql-java = { module = "com.graphql-java:graphql-java", version.ref = "graphql-java" }
graphql-java-extended-scalars = { module = "com.graphql-java:graphql-java-extended-scalars", version.ref = "graphql-java-extended-scalars" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-bom = { module = "org.mockito:mockito-bom", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter" }
